config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jungles

  resources :topics do
    member do #anything with member route assumes that it needs an ID to find the member
      post 'upvote'
      post 'downvote'
    end
  end

  root 'topics#index'

end

app/models/jungle.rb
class Jungle < ActiveRecord::Base
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :votes, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jungles_controller.rb
class JunglesController < ApplicationController
  before_action :set_jungle, only: [:show, :edit, :update, :destroy]

  # GET /jungles
  # GET /jungles.json
  def index
    @jungles = Jungle.all
  end

  # GET /jungles/1
  # GET /jungles/1.json
  def show
  end

  # GET /jungles/new
  def new
    @jungle = Jungle.new
  end

  # GET /jungles/1/edit
  def edit
  end

  # POST /jungles
  # POST /jungles.json
  def create
    @jungle = Jungle.new(jungle_params)

    respond_to do |format|
      if @jungle.save
        format.html { redirect_to @jungle, notice: 'Jungle was successfully created.' }
        format.json { render :show, status: :created, location: @jungle }
      else
        format.html { render :new }
        format.json { render json: @jungle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jungles/1
  # PATCH/PUT /jungles/1.json
  def update
    respond_to do |format|
      if @jungle.update(jungle_params)
        format.html { redirect_to @jungle, notice: 'Jungle was successfully updated.' }
        format.json { render :show, status: :ok, location: @jungle }
      else
        format.html { render :edit }
        format.json { render json: @jungle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jungles/1
  # DELETE /jungles/1.json
  def destroy
    @jungle.destroy
    respond_to do |format|
      format.html { redirect_to jungles_url, notice: 'Jungle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jungle
      @jungle = Jungle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jungle_params
      params.require(:jungle).permit(:monkey, :eats)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show, :index]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to topics_path, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def upvote #method
    @topic = Topic.find(params[:id])
    @topic.votes.create
    redirect_to(topics_path)
  end
  
  def downvote
    @topic = Topic.find(params[:id])
    if @topic.votes.count > 0
      @topic.votes.first.destroy
    end
    redirect_to(topics_path)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jungles_helper.rb
module JunglesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/jungles/_form.html.erb
<%= form_for(@jungle) do |f| %>
  <% if @jungle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jungle.errors.count, "error") %> prohibited this jungle from being saved:</h2>

      <ul>
      <% @jungle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :monkey %><br>
    <%= f.text_field :monkey %>
  </div>
  <div class="field">
    <%= f.label :eats %><br>
    <%= f.text_field :eats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jungles/edit.html.erb
<h1>Editing jungle</h1>

<%= render 'form' %>

<%= link_to 'Show', @jungle %> |
<%= link_to 'Back', jungles_path %>

app/views/jungles/index.html.erb
<h1>Listing jungles</h1>

<table>
  <thead>
    <tr>
      <th>Monkey</th>
      <th>Eats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jungles.each do |jungle| %>
      <tr>
        <td><%= jungle.monkey %></td>
        <td><%= jungle.eats %></td>
        <td><%= link_to 'Show', jungle %></td>
        <td><%= link_to 'Edit', edit_jungle_path(jungle) %></td>
        <td><%= link_to 'Destroy', jungle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Jungle', new_jungle_path %>

app/views/jungles/new.html.erb
<h1>New jungle</h1>

<%= render 'form' %>

<%= link_to 'Back', jungles_path %>

app/views/jungles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Monkey:</strong>
  <%= @jungle.monkey %>
</p>

<p>
  <strong>Eats:</strong>
  <%= @jungle.eats %>
</p>

<%= link_to 'Edit', edit_jungle_path(@jungle) %> |
<%= link_to 'Back', jungles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Suggestotron</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  
  <% if user_signed_in? %>
  Logged in as <%= current_user.email %>
  <%= link_to 'Edit Profile', edit_user_registration_path %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Sign up', new_user_registration_path %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>

  
<%= yield %>

</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<p id='notice'><%= notice %></p>
<table>
  <thead>
    <tr>
      <th>Title</th>
<!--       <th>Description</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
   <% @topics.each do |topic| %>
  <tr>
    <td><%= link_to topic.title, topic %></td>
<!--     <td><%= topic.description %></td> -->
    <td><%= pluralize(topic.votes.count, "vote") %></td>
    <td><%= button_to '+1', upvote_topic_path(topic), method: :post %></td>
    <td><%= button_to '-1', downvote_topic_path(topic), method: :post %></td>
<!--     <td><%= link_to 'Show', topic %></td> -->
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_topic_path %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>